version: '3.1'

services:

  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - "5432:5432"
    volumes: 
        - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123qwe
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"